extends Node

@warning_ignore("unused_signal")
signal combat_started(enemy_data: Array)
@warning_ignore("unused_signal")
signal combat_ended(victory: bool)
@warning_ignore("unused_signal")
signal player_attacked(sector: int, damage: float, was_timed: bool, heading: Vector2)
@warning_ignore("unused_signal")
signal player_parried(sector: int, quality: String, reflect_damage: float, heading: Vector2)
@warning_ignore("unused_signal")
signal player_dodged(from_sector: int, to_sector: int, heading: Vector2)
@warning_ignore("unused_signal")
signal player_teleported(from_sector: int, to_sector: int)
@warning_ignore("unused_signal")
signal combat_input_resolved(action: String, sector: int, accepted: bool, buffered: bool, reason: String, state: String, cooldowns: Dictionary)
@warning_ignore("unused_signal")
signal timed_attack_resolved(sector: int, quality: String, damage: float, enemy_id: int)
@warning_ignore("unused_signal")
signal attack_timing_early_resolved(sector: int)
@warning_ignore("unused_signal")
signal player_took_damage(amount: float, source_sector: int)
@warning_ignore("unused_signal")
signal player_died()
@warning_ignore("unused_signal")
signal player_healed(amount: float)
@warning_ignore("unused_signal")
signal player_no_stamina()
@warning_ignore("unused_signal")
signal player_bleed_changed(stacks: int, max_stacks: int)
@warning_ignore("unused_signal")
signal enemy_damaged(enemy_id: int, damage: float)
@warning_ignore("unused_signal")
signal enemy_defeated(enemy_id: int)
@warning_ignore("unused_signal")
signal enemy_status_applied(enemy_id: int, status_id: String, params: Dictionary)
@warning_ignore("unused_signal")
signal enemy_status_cleared(enemy_id: int)
@warning_ignore("unused_signal")
signal enemy_status_applied_requested(enemy_id: int, status_id: String, params: Dictionary)
@warning_ignore("unused_signal")
signal enemy_bleed_changed(enemy_id: int, stacks: int, max_stacks: int)
@warning_ignore("unused_signal")
signal enemy_ruptured(enemy_id: int, total_damage: float)
@warning_ignore("unused_signal")
signal enemy_attack_telegraphed(enemy_id: int, sector: int, world_pos: Vector2, windup: float)
@warning_ignore("unused_signal")
signal enemy_attack_telegraph_cancelled(enemy_id: int)
@warning_ignore("unused_signal")
signal combo_changed(count: int, tier: String)
@warning_ignore("unused_signal")
signal combo_broken(combo_count: int)
@warning_ignore("unused_signal")
signal phrase_milestone(count: int)
@warning_ignore("unused_signal")
signal tier_changed(new_tier: String, old_tier: String)
@warning_ignore("unused_signal")
signal stamina_changed(current: float, maximum: float)
@warning_ignore("unused_signal")
signal style_changed(score: float, tier: String)
@warning_ignore("unused_signal")
signal ultimate_available()
@warning_ignore("unused_signal")
signal ultimate_fired(power: float)
@warning_ignore("unused_signal")
signal ultimate_power_granted(amount: float)
