extends Node

# Combat lifecycle
@warning_ignore("unused_signal")
signal combat_started(enemy_data: Array)
@warning_ignore("unused_signal")
signal combat_ended(victory: bool)
@warning_ignore("unused_signal")
signal run_started()
@warning_ignore("unused_signal")
signal capture_offered(creature_data: Dictionary)
@warning_ignore("unused_signal")
signal sovereign_threshold_reached(ratio: float)
@warning_ignore("unused_signal")
signal boss_outcome_resolved(victory: bool, data: Dictionary)
@warning_ignore("unused_signal")
signal boss_phase_transitioned(phase_index: int)

# Projectile flow
@warning_ignore("unused_signal")
signal player_attacked(sector: int, damage: float, quality: String)
@warning_ignore("unused_signal")
signal player_parried(sector: int, quality: String, reflect_damage: float)
@warning_ignore("unused_signal")
signal player_dodged(from_sector: int, to_sector: int)
@warning_ignore("unused_signal")
signal player_teleported(from_sector: int, to_sector: int)
@warning_ignore("unused_signal")
signal combat_input_resolved(action: String, sector: int, quality: String)
@warning_ignore("unused_signal")
signal timed_attack_resolved(sector: int, quality: String, damage: float, enemy_id: int)
@warning_ignore("unused_signal")
signal attack_timing_early_resolved(sector: int, quality: String, damage: float, enemy_id: int)

# Player state
@warning_ignore("unused_signal")
signal player_took_damage(amount: float, source_sector: int)
@warning_ignore("unused_signal")
signal player_died()
@warning_ignore("unused_signal")
signal player_healed(amount: float)
@warning_ignore("unused_signal")
signal player_no_stamina()
@warning_ignore("unused_signal")
signal player_bleed_changed(stacks: int, max_stacks: int)

# Enemy state
@warning_ignore("unused_signal")
signal enemy_damaged(enemy_id: int, damage: float)
@warning_ignore("unused_signal")
signal enemy_defeated(enemy_id: int)
@warning_ignore("unused_signal")
signal enemy_status_applied(sector: int, status_id: String, params: Dictionary)
@warning_ignore("unused_signal")
signal enemy_status_cleared(sector: int)
@warning_ignore("unused_signal")
signal enemy_status_applied_requested(enemy_id: int, status_id: String, params: Dictionary)
@warning_ignore("unused_signal")
signal enemy_bleed_changed(enemy_id: int, stacks: int, max_stacks: int)
@warning_ignore("unused_signal")
signal enemy_ruptured(enemy_id: int, total_damage: float)

# Combat meter
@warning_ignore("unused_signal")
signal combo_changed(count: int, tier: String)
@warning_ignore("unused_signal")
signal combo_broken()
@warning_ignore("unused_signal")
signal phrase_milestone(count: int)
@warning_ignore("unused_signal")
signal tier_changed(tier: String)

# Presentation / Juice
@warning_ignore("unused_signal")
signal screen_flash(color: Color, duration: float)
@warning_ignore("unused_signal")
signal screen_shake(intensity: float, duration: float)
@warning_ignore("unused_signal")
signal ui_shake(intensity: float, duration: float)
@warning_ignore("unused_signal")
signal slow_motion(scale: float, duration: float)
@warning_ignore("unused_signal")
signal play_sfx(sfx_id: String)
@warning_ignore("unused_signal")
signal timing_ring_pressed(sector: int)
@warning_ignore("unused_signal")
signal song_beat_pulse(beat_index: int, intensity: float, quality: String)
@warning_ignore("unused_signal")
signal dna_resonated(species_id: String, amount: float)
@warning_ignore("unused_signal")
signal projectile_fired(sector: int, enemy_id: int)
@warning_ignore("unused_signal")
signal projectile_missed(sector: int, damage: float)
@warning_ignore("unused_signal")
signal proc_feedback_requested(text: String, color: Color)
@warning_ignore("unused_signal")
signal impact_burst_requested(profile: Dictionary, sector: int, enemy_id: int)

# Metagame / Progression
@warning_ignore("unused_signal")
signal run_completed(victory: bool)
@warning_ignore("unused_signal")
signal limit_breaker_triggered(achievement_id: String)
@warning_ignore("unused_signal")
signal creature_bonded(creature_data: Dictionary)
@warning_ignore("unused_signal")
signal creature_eaten(creature_data: Dictionary)
@warning_ignore("unused_signal")
signal run_growth_changed(type: String, amount: float)
@warning_ignore("unused_signal")
signal run_growth_level_resolved(type: String, level: int)
@warning_ignore("unused_signal")
signal tendency_growth_resolved(type: String, amount: float)
@warning_ignore("unused_signal")
signal dna_gained(species_id: String, amount: float)
@warning_ignore("unused_signal")
signal dna_routing_changed(routes: Dictionary)
@warning_ignore("unused_signal")
signal support_charge_changed(current: float, maximum: float)
@warning_ignore("unused_signal")
signal bonded_support_triggered(species_id: String)
@warning_ignore("unused_signal")
signal dna_lock_denied(species_id: String, current: float, required: float)
@warning_ignore("unused_signal")
signal vessel_shifted(class_data: Dictionary)
@warning_ignore("unused_signal")
signal mastery_context_updated(mastery_data: Dictionary)
@warning_ignore("unused_signal")
signal quig_narrative_triggered(text: String, color: Color)
@warning_ignore("unused_signal")
signal stamina_changed(current: float, maximum: float)
@warning_ignore("unused_signal")
signal style_changed(score: float, tier: String)
@warning_ignore("unused_signal")
signal ultimate_available(is_available: bool)
@warning_ignore("unused_signal")
signal ultimate_fired()
@warning_ignore("unused_signal")
signal ultimate_power_granted(amount: float)
