extends Node

# Combat lifecycle
@warning_ignore("unused_signal")
signal combat_started(enemy_data: Array)
@warning_ignore("unused_signal")
signal combat_ended(victory: bool)
@warning_ignore("unused_signal")
signal run_started(run_number: int)
@warning_ignore("unused_signal")
signal sovereign_threshold_reached(ratio: float)
@warning_ignore("unused_signal")
signal sovereign_reached()
@warning_ignore("unused_signal")
signal boss_outcome_resolved(victory: bool, data: Dictionary)
@warning_ignore("unused_signal")
signal boss_phase_transitioned(phase_index: int)

# Projectile flow
@warning_ignore("unused_signal")
signal player_attacked(sector: int, damage: float, was_timed: bool, heading: Vector2)
@warning_ignore("unused_signal")
signal player_parried(sector: int, quality: String, reflect_damage: float, heading: Vector2)
@warning_ignore("unused_signal")
signal player_dodged(from_sector: int, to_sector: int, heading: Vector2)
@warning_ignore("unused_signal")
signal player_teleported(from_sector: int, to_sector: int)
@warning_ignore("unused_signal")
signal combat_input_resolved(action: String, sector: int, accepted: bool, buffered: bool, reason: String, state: String, cooldowns: Dictionary)
@warning_ignore("unused_signal")
signal timed_attack_resolved(sector: int, quality: String, damage: float, enemy_id: int)
@warning_ignore("unused_signal")
signal attack_timing_early_resolved(sector: int)

# Player state
@warning_ignore("unused_signal")
signal player_took_damage(amount: float, source_sector: int)
@warning_ignore("unused_signal")
signal player_died()
@warning_ignore("unused_signal")
signal player_healed(amount: float)
@warning_ignore("unused_signal")
signal player_no_stamina()
@warning_ignore("unused_signal")
signal player_bleed_changed(stacks: int, max_stacks: int)

# Enemy state
@warning_ignore("unused_signal")
signal enemy_damaged(enemy_id: int, damage: float)
@warning_ignore("unused_signal")
signal enemy_defeated(enemy_id: int)
@warning_ignore("unused_signal")
signal enemy_status_applied(enemy_id: int, status_id: String, params: Dictionary)
@warning_ignore("unused_signal")
signal enemy_status_cleared(enemy_id: int)
@warning_ignore("unused_signal")
signal enemy_status_applied_requested(enemy_id: int, status_id: String, params: Dictionary)
@warning_ignore("unused_signal")
signal enemy_bleed_changed(enemy_id: int, stacks: int, max_stacks: int)
@warning_ignore("unused_signal")
signal enemy_ruptured(enemy_id: int, total_damage: float)
@warning_ignore("unused_signal")
signal enemy_attack_telegraphed(enemy_id: int, sector: int, world_pos: Vector2, windup: float)
@warning_ignore("unused_signal")
signal enemy_attack_telegraph_cancelled(enemy_id: int)

# Combat meter
@warning_ignore("unused_signal")
signal combo_changed(count: int, tier: String)
@warning_ignore("unused_signal")
signal combo_broken(combo_count: int)
@warning_ignore("unused_signal")
signal phrase_milestone(count: int)
@warning_ignore("unused_signal")
signal tier_changed(new_tier: String, old_tier: String)

# Presentation / Juice
@warning_ignore("unused_signal")
signal screen_flash(color: Color, duration: float)
@warning_ignore("unused_signal")
signal screen_shake(intensity: float, duration: float)
@warning_ignore("unused_signal")
signal ui_shake(intensity: float, duration: float)
@warning_ignore("unused_signal")
signal slow_motion(scale: float, duration: float)
@warning_ignore("unused_signal")
signal play_sfx(sfx_id: String)
@warning_ignore("unused_signal")
signal timing_ring_pressed(sector: int)
@warning_ignore("unused_signal")
signal song_beat_pulse(beat_index: int, intensity: float, quality: String)
@warning_ignore("unused_signal")
signal dna_resonated(species_id: String, amount: float)
@warning_ignore("unused_signal")
signal projectile_fired(sector: int, enemy_id: int)
@warning_ignore("unused_signal")
signal projectile_missed(sector: int, damage: float)
@warning_ignore("unused_signal")
signal proc_feedback_requested(text: String, color: Color)
@warning_ignore("unused_signal")
signal impact_burst_requested(profile: Dictionary, sector: int, enemy_id: int)

# Metagame / Progression
@warning_ignore("unused_signal")
signal run_completed(victory: bool)
@warning_ignore("unused_signal")
signal limit_breaker_triggered(achievement_id: String)
@warning_ignore("unused_signal")
signal creature_bonded(creature_data: Dictionary)
@warning_ignore("unused_signal")
signal creature_eaten(creature_data: Dictionary)
@warning_ignore("unused_signal")
signal capture_offered(creature_data: Dictionary)
@warning_ignore("unused_signal")
signal creature_ascended(data: Dictionary)
@warning_ignore("unused_signal")
signal world_fate_shifted(new_fate_id: String, old_fate_id: String)
@warning_ignore("unused_signal")
signal world_fate_changed(fate_snapshot: Dictionary)
@warning_ignore("unused_signal")
signal run_growth_changed(level: int, current_exp: float, exp_to_next: float)
@warning_ignore("unused_signal")
signal run_growth_level_resolved(result: Dictionary)
@warning_ignore("unused_signal")
signal tendency_growth_resolved(tendency_id: String, title: String, summary: String)
@warning_ignore("unused_signal")
signal creature_exp_changed(species_id: String, current_exp: float, exp_to_next: float)
@warning_ignore("unused_signal")
signal creature_leveled_up(species_id: String, new_level: int)
@warning_ignore("unused_signal")
signal dna_gained(species_id: String, amount: float, total: float)
@warning_ignore("unused_signal")
signal dna_routing_changed(route_id: String, label: String)
@warning_ignore("unused_signal")
signal support_charge_changed(current: float, maximum: float, active_species_id: String)
@warning_ignore("unused_signal")
signal bonded_support_triggered(species_id: String, sector: int, effect_id: String)
@warning_ignore("unused_signal")
signal support_manual_activation_requested(sector: int, quality: String)
@warning_ignore("unused_signal")
signal dna_lock_denied(species_id: String, current: float, required: float)
@warning_ignore("unused_signal")
signal vessel_shifted(class_data: Dictionary)
@warning_ignore("unused_signal")
signal mastery_context_updated(mastery_data: Dictionary)
@warning_ignore("unused_signal")
signal quig_narrative_triggered(text: String, duration: float)
@warning_ignore("unused_signal")
signal tempo_state_entered(state_id: String)
@warning_ignore("unused_signal")
signal stamina_changed(current: float, maximum: float)
@warning_ignore("unused_signal")
signal style_changed(score: float, tier: String)
@warning_ignore("unused_signal")
signal ultimate_available()
@warning_ignore("unused_signal")
signal ultimate_fired(power: float)
@warning_ignore("unused_signal")
signal ultimate_power_granted(amount: float)


func _ready() -> void:
	# CombatBus forwarding
	combat_started.connect(CombatBus.combat_started.emit)
	combat_ended.connect(CombatBus.combat_ended.emit)
	player_attacked.connect(CombatBus.player_attacked.emit)
	player_parried.connect(CombatBus.player_parried.emit)
	player_dodged.connect(CombatBus.player_dodged.emit)
	player_teleported.connect(CombatBus.player_teleported.emit)
	combat_input_resolved.connect(CombatBus.combat_input_resolved.emit)
	timed_attack_resolved.connect(CombatBus.timed_attack_resolved.emit)
	attack_timing_early_resolved.connect(CombatBus.attack_timing_early_resolved.emit)
	player_took_damage.connect(CombatBus.player_took_damage.emit)
	player_died.connect(CombatBus.player_died.emit)
	player_healed.connect(CombatBus.player_healed.emit)
	player_no_stamina.connect(CombatBus.player_no_stamina.emit)
	player_bleed_changed.connect(CombatBus.player_bleed_changed.emit)
	enemy_damaged.connect(CombatBus.enemy_damaged.emit)
	enemy_defeated.connect(CombatBus.enemy_defeated.emit)
	enemy_status_applied.connect(CombatBus.enemy_status_applied.emit)
	enemy_status_cleared.connect(CombatBus.enemy_status_cleared.emit)
	enemy_status_applied_requested.connect(CombatBus.enemy_status_applied_requested.emit)
	enemy_bleed_changed.connect(CombatBus.enemy_bleed_changed.emit)
	enemy_ruptured.connect(CombatBus.enemy_ruptured.emit)
	enemy_attack_telegraphed.connect(CombatBus.enemy_attack_telegraphed.emit)
	enemy_attack_telegraph_cancelled.connect(CombatBus.enemy_attack_telegraph_cancelled.emit)
	combo_changed.connect(CombatBus.combo_changed.emit)
	combo_broken.connect(CombatBus.combo_broken.emit)
	phrase_milestone.connect(CombatBus.phrase_milestone.emit)
	tier_changed.connect(CombatBus.tier_changed.emit)
	stamina_changed.connect(CombatBus.stamina_changed.emit)
	style_changed.connect(CombatBus.style_changed.emit)
	ultimate_available.connect(CombatBus.ultimate_available.emit)
	ultimate_fired.connect(CombatBus.ultimate_fired.emit)
	ultimate_power_granted.connect(CombatBus.ultimate_power_granted.emit)

	# MetaBus forwarding
	run_started.connect(MetaBus.run_started.emit)
	run_completed.connect(MetaBus.run_completed.emit)
	limit_breaker_triggered.connect(MetaBus.limit_breaker_triggered.emit)
	creature_bonded.connect(MetaBus.creature_bonded.emit)
	creature_eaten.connect(MetaBus.creature_eaten.emit)
	capture_offered.connect(MetaBus.capture_offered.emit)
	creature_ascended.connect(MetaBus.creature_ascended.emit)
	world_fate_shifted.connect(MetaBus.world_fate_shifted.emit)
	world_fate_changed.connect(MetaBus.world_fate_changed.emit)
	run_growth_changed.connect(MetaBus.run_growth_changed.emit)
	run_growth_level_resolved.connect(MetaBus.run_growth_level_resolved.emit)
	tendency_growth_resolved.connect(MetaBus.tendency_growth_resolved.emit)
	creature_exp_changed.connect(MetaBus.creature_exp_changed.emit)
	creature_leveled_up.connect(MetaBus.creature_leveled_up.emit)
	dna_gained.connect(MetaBus.dna_gained.emit)
	dna_routing_changed.connect(MetaBus.dna_routing_changed.emit)
	support_charge_changed.connect(MetaBus.support_charge_changed.emit)
	bonded_support_triggered.connect(MetaBus.bonded_support_triggered.emit)
	support_manual_activation_requested.connect(MetaBus.support_manual_activation_requested.emit)
	dna_lock_denied.connect(MetaBus.dna_lock_denied.emit)
	vessel_shifted.connect(MetaBus.vessel_shifted.emit)
	mastery_context_updated.connect(MetaBus.mastery_context_updated.emit)
	quig_narrative_triggered.connect(MetaBus.quig_narrative_triggered.emit)
	sovereign_threshold_reached.connect(MetaBus.sovereign_threshold_reached.emit)
	sovereign_reached.connect(MetaBus.sovereign_reached.emit)
	boss_outcome_resolved.connect(MetaBus.boss_outcome_resolved.emit)
	boss_phase_transitioned.connect(MetaBus.boss_phase_transitioned.emit)
	tempo_state_entered.connect(MetaBus.tempo_state_entered.emit)

	# JuiceBus forwarding
	screen_flash.connect(JuiceBus.screen_flash.emit)
	screen_shake.connect(JuiceBus.screen_shake.emit)
	ui_shake.connect(JuiceBus.ui_shake.emit)
	slow_motion.connect(JuiceBus.slow_motion.emit)
	play_sfx.connect(JuiceBus.play_sfx.emit)
	timing_ring_pressed.connect(JuiceBus.timing_ring_pressed.emit)
	song_beat_pulse.connect(JuiceBus.song_beat_pulse.emit)
	dna_resonated.connect(JuiceBus.dna_resonated.emit)
	projectile_fired.connect(JuiceBus.projectile_fired.emit)
	projectile_missed.connect(JuiceBus.projectile_missed.emit)
	proc_feedback_requested.connect(JuiceBus.proc_feedback_requested.emit)
	impact_burst_requested.connect(JuiceBus.impact_burst_requested.emit)
