extends Node

@warning_ignore("unused_signal")
signal screen_flash(color: Color, duration: float)
@warning_ignore("unused_signal")
signal screen_shake(intensity: float, duration: float)
@warning_ignore("unused_signal")
signal ui_shake(intensity: float, duration: float)
@warning_ignore("unused_signal")
signal slow_motion(scale: float, duration: float)
@warning_ignore("unused_signal")
signal play_sfx(sfx_id: String)
@warning_ignore("unused_signal")
signal timing_ring_pressed(sector: int)
@warning_ignore("unused_signal")
signal song_beat_pulse(beat_index: int, intensity: float, quality: String)
@warning_ignore("unused_signal")
signal dna_resonated(species_id: String, amount: float)
@warning_ignore("unused_signal")
signal projectile_fired(sector: int, enemy_id: int)
@warning_ignore("unused_signal")
signal projectile_missed(sector: int, damage: float)
@warning_ignore("unused_signal")
signal proc_feedback_requested(text: String, color: Color)
@warning_ignore("unused_signal")
signal impact_burst_requested(profile: Dictionary, sector: int, enemy_id: int)
