extends Node

@warning_ignore("unused_signal")
signal run_started(run_number: int)
@warning_ignore("unused_signal")
signal run_completed(victory: bool)
@warning_ignore("unused_signal")
signal limit_breaker_triggered(achievement_id: String)
@warning_ignore("unused_signal")
signal creature_bonded(creature_data: Dictionary)
@warning_ignore("unused_signal")
signal creature_eaten(creature_data: Dictionary)
@warning_ignore("unused_signal")
signal capture_offered(creature_data: Dictionary)
@warning_ignore("unused_signal")
signal creature_ascended(data: Dictionary)
@warning_ignore("unused_signal")
signal world_fate_shifted(new_fate_id: String, old_fate_id: String)
@warning_ignore("unused_signal")
signal world_fate_changed(fate_snapshot: Dictionary)
@warning_ignore("unused_signal")
signal run_growth_changed(level: int, current_exp: float, exp_to_next: float)
@warning_ignore("unused_signal")
signal run_growth_level_resolved(result: Dictionary)
@warning_ignore("unused_signal")
signal tendency_growth_resolved(tendency_id: String, title: String, summary: String)
@warning_ignore("unused_signal")
signal creature_exp_changed(species_id: String, current_exp: float, exp_to_next: float)
@warning_ignore("unused_signal")
signal creature_leveled_up(species_id: String, new_level: int)
@warning_ignore("unused_signal")
signal dna_gained(species_id: String, amount: float, total: float)
@warning_ignore("unused_signal")
signal dna_routing_changed(route_id: String, label: String)
@warning_ignore("unused_signal")
signal support_charge_changed(current: float, maximum: float, active_species_id: String)
@warning_ignore("unused_signal")
signal bonded_support_triggered(species_id: String, sector: int, effect_id: String)
@warning_ignore("unused_signal")
signal support_manual_activation_requested(sector: int, quality: String)
@warning_ignore("unused_signal")
signal dna_lock_denied(species_id: String, current: float, required: float)
@warning_ignore("unused_signal")
signal vessel_shifted(class_data: Dictionary)
@warning_ignore("unused_signal")
signal mastery_context_updated(mastery_data: Dictionary)
@warning_ignore("unused_signal")
signal quig_narrative_triggered(text: String, duration: float)
@warning_ignore("unused_signal")
signal sovereign_threshold_reached(ratio: float)
@warning_ignore("unused_signal")
signal sovereign_reached()
@warning_ignore("unused_signal")
signal boss_outcome_resolved(victory: bool, data: Dictionary)
@warning_ignore("unused_signal")
signal boss_phase_transitioned(phase_index: int)
@warning_ignore("unused_signal")
signal tempo_state_entered(state_id: String)
